# Generated by Django 4.1.3 on 2022-11-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=2)),
                ("data", models.CharField(max_length=9)),
                ("valor", models.CharField(max_length=11)),
                ("cpf", models.CharField(max_length=12)),
                ("cartao", models.CharField(max_length=13)),
                ("hora", models.CharField(max_length=7)),
                ("dono_loja", models.CharField(max_length=15)),
                ("nome_loja", models.CharField(max_length=20)),
            ],
        ),
    ]
